### ISSUE TITLE
Deserialization error due to decimal point symbol 

### ISSUE THREAD

**Issue by GutZuFusss** [the-marenga/sf-server#1]
This one actually took me long to figure out, but the official SF client seems to seriously use a comma instead of a point (german notation) for (at least) the "rnd" parameter in the `/req.php` requests.

I am at a loss of words, I want my 1 POINT 5 hours back.

**Comment by GutZuFusss** [comment]
Changing the type from float to string seems to to the trick. After some more fiddeling I am able to get ingame with the current, official client 🥳 

Although I can't yet load up the quests, but thats for another issue :D

**Comment by the-marenga** [comment]
Server uses axum now and completely ignores the rnd part, so this should be fixes on main already
