### ISSUE TITLE
Containerize setup (+ some more related ideas)

### ISSUE THREAD

**Issue by GutZuFusss** [the-marenga/sf-server#16]
Hi,

if you think any of my ideas below would be something you agree would be nice to have for this project, please let me know, and I would be happy to shoot you a PR, as this is something my dumbass could contribute.

1. Create a Dockerfile to create an image for the main executable
**1.1**  I think it would be nice to then build an image from a CI/CD pipeline, though I see this project does not yet have one, so I would also offer my help here
3. Create a Docker stack/swarm config (please see list item 2.1 and 3. on why this could be sensible)
**2.1**  This includes mounting the DB file for external access, as well as any configuration in the future (also logs, when it comes to it). In my opinion this alone could justify having a stack conf for possibly only a single container (if you don't like 3.), because mounting files via the "docker run ..." CLI command is quite tedious
4. Make the DBMS configurable
**3.1** I could also integrate tests into the CI/CD pipeline that ensure, that all changes run for our target DBMSs. I would suggest to keep it simple here and go with SQLite and just Postgres for a server-based DBMS, as adding support for more usually just results in edge cases you really don't want to deal with unless you abolutely have to
**3.2** Depending on the configured DBMS we could then also spin up a Postgres container
5. It goes without saying that I can also write documentation on all of the points above, I think this is of particular interest if you don't like the stack/swarm idea, because that will make mounting files and configuration (setting the `DB_URL` environment variable, ...) require a little more advanced knowledge of Docker and containerization

Please let me know what you think about these ideas and I will get to work :)

**Comment by the-marenga** [comment]
Thanks. Yeah, that sounds interesting and probably works great for business environment, but for something that mainly I work on, this is just overkill. I enjoy the basic github workflow I have setup for the api (https://github.com/the-marenga/sf-api/blob/main/.github/workflows/rust.yml) and building releases for the helper (https://github.com/the-marenga/sf-scrapbook-helper/blob/main/.github/workflows/release.yml) is also a great thing, but that is all I need. I appreciate your willingness to help with setting up a custom docker pipeline, but in the longterm this would be my responsibility to maintain and I am going to do for this repo here. 

If there is any amount of non trivial PRs in the future, I am going to setup a cargo check pipeline, that runs `sqlx database create && sqlx migrate run && cargo check` and thats about it. If this ever gets a real release, I would have to add `sqlx::migrate!` in the application to do migrations on the user end and adjust the sf-helper build script to build this here, but that would cover the requirements I have for CI/CD.

I am focusing on keeping this project as simple as possible. Any "support multiple DB types" plans would come with compile time cfg! flags everywhere in the code and would just not be worth it for me. I will keep this in mind for the future though. 

Just as a heads up, I am currently exploring open sourcing & fixing the MFBot. Depending on how that goes, I might be very distracted with that project for the next few days/weeks

**Comment by GutZuFusss** [comment]
not sure how that is considered enterprise, I even ran MFBot in containers back in the days :D It's just easier to manage.

but ok, looking forward to a MFBot update :) then I guess I will try to implement PvP fights myself, lets see if I can use your sf-api for that
