### ISSUE TITLE
AccountCreate fails at quest insertion to DB

### ISSUE THREAD

**Issue by GutZuFusss** [the-marenga/sf-server#2]
Here is my attempt of printing an error message, not sure how useful this is to anyone:
`Error inserting quest: Database(PgDatabaseError { severity: Error, code: "23502", message: "null value in column \"xp\" of relation \"quest\" violates not-null constraint", detail: Some("Failing row contains (8, 1, 1, 139, 1, 60, null, null, 0, null)."), hint: None, position: None, where: None, schema: Some("public"), table: Some("quest"), column: Some("xp"), data_type: None, constraint: None, file: Some("execMain.c"), line: Some(1987), routine: Some("ExecConstraints") })`

**Comment by the-marenga** [comment]
See #4
